GOEDEL_APPARIX=true
# set basic completion style, to show a menu and cycle through, using LS_COLORS
# to highlight directories
setopt menucomplete
zstyle ':completion:*' menu select=1
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
source "$APPARIXHOME/appari.sh"
# to let the dummy clobber apparix rc files
unsetopt noclobber
source "$APPARIXHOME/dummy_apparish_init.sh"
# Only draw one rprompt at any time
setopt transient_rprompt
source "$APPARIXHOME/prompt.zsh"
